### ISSUE TITLE
Error running running_piwind.ipynb with python 3.5.5

### ISSUE THREAD

**Issue by martvdmarel** [OasisLMF/OasisPiWind#15]
In running `running_piwind.ipynb`, with python 3.5.5 and Jupyter notebook 4.2.3

For cell 16:
```
! rm -rf /tmp/analysis_test
! oasislmf model run -C oasislmf.json -r /tmp/analysis_test
```

the following error:
```
Creating temporary folder /tmp/analysis_test/tmp for Oasis files
Getting model info and creating lookup service instance
STARTED: keys_server.PiWind.PiWindKeysLookup.__init__
STARTED: oasislmf.keys.lookup.__init__
COMPLETED: oasislmf.keys.lookup.__init__ in 0.0s
COMPLETED: keys_server.PiWind.PiWindKeysLookup.__init__ in 0.05s
	{'model_id': 'PiWind', 'supplier_id': 'OasisLMF', 'model_version_id': '0.0.0.1'}, <keys_server.PiWind.PiWindKeysLookup.PiWindKeysLookup object at 0x7f385d007be0>
Creating Oasis model object
	<class 'oasislmf.models.model.OasisModel'>: {'_model_version_id': '0.0.0.1', '_model_id': 'PiWind', '_supplier_id': 'OasisLMF', '_key': 'OasisLMF/PiWind/0.0.0.1', '_resources': {'canonical_exposures_profile': {'WSCV5VAL': {}, 'COUNTYCODE': {}, 'YEARUPGRAD': {}, 'WSCV5DED': {}, 'WSCV7LIMIT': {}, 'NUMBLDGS': {}, 'BLDGCLASS': {}, 'WSCV1LIMIT': {'PerilID': 1, 'FMTermGroupID': 1, 'CoverageTypeID': 1, 'ProfileType': 'Loc', 'FMTermType': 'Limit', 'ProfileElementName': 'WSCV1LIMIT', 'FMLevel': 1, 'FMLevelName': 'Coverage', 'FieldName': 'CoverageLimit'}, 'COND1NAME': {'FieldName': 'SubLimitReference', 'ProfileElementName': 'COND1NAME'}, 'COND1TYPE': {}, 'WSCV3DED': {}, 'COND1DEDUCTIBLE': {'DeductibleType': 'B', 'FMTermGroupID': 1, 'ProfileType': 'Loc', 'FMTermType': 'Deductible', 'ProfileElementName': 'COND1DEDUCTIBLE', 'FMLevel': 4, 'FMLevelName': 'Sublimit', 'FieldName': 'SubLimitDeductible'}, 'CITYCODE': {}, 'WSCV1VAL': {'PerilID': 1, 'FMTermGroupID': 1, 'CoverageTypeID': 1, 'ProfileType': 'Loc', 'FMTermType': 'TIV', 'ProfileElementName': 'WSCV1VAL', 'FMLevel': 1, 'FMLevelName': 'Coverage', 'FieldName': 'TIV'}, 'POSTALCODE': {}, 'WSSITELIM': {'FMTermGroupID': 1, 'ProfileType': 'Loc', 'FMTermType': 'Limit', 'ProfileElementName': 'WSSITELIM', 'FMLevel': 3, 'FMLevelName': 'Site', 'FieldName': 'SiteLimit'}, 'ADDRMATCH': {}, 'LATITUDE': {}, 'WSCV2VAL': {}, 'ROOFGEOM': {}, 'CNTRYCODE': {}, 'WSCV6LIMIT': {}, 'WSCV3LIMIT': {}, 'WSCV8DED': {}, 'WSCV9DED': {}, 'WSCV4LIMIT': {'PerilID': 1, 'FMTermGroupID': 2, 'CoverageTypeID': 1, 'ProfileType': 'Loc', 'FMTermType': 'Limit', 'ProfileElementName': 'WSCV4LIMIT', 'FMLevel': 1, 'FMLevelName': 'Coverage', 'FieldName': 'CoverageLimit'}, 'COND1LIMIT': {'FMTermGroupID': 1, 'ProfileType': 'Loc', 'FMTermType': 'Limit', 'ProfileElementName': 'COND1LIMIT', 'FMLevel': 4, 'FMLevelName': 'Sublimit', 'FieldName': 'SubLimitLimit'}, 'WSCV7VAL': {}, 'WSCV9LIMIT': {}, 'CNTRYSCHEME': {}, 'STATE': {}, 'WSCV9VAL': {}, 'CITY': {}, 'WSCOMBINEDDED': {'DeductibleType': 'B', 'FMTermGroupID': 1, 'ProfileType': 'Loc', 'FMTermType': 'Deductible', 'ProfileElementName': 'WSCOMBINEDDED', 'FMLevel': 2, 'FMLevelName': 'Combined', 'FieldName': 'CombinedDeductible'}, 'WSCV2DED': {}, 'WSCV3VAL': {}, 'LOCNUM': {}, 'WSCV1DED': {'PerilID': 1, 'DeductibleType': 'B', 'CoverageTypeID': 1, 'FMTermGroupID': 1, 'FMTermType': 'Deductible', 'ProfileElementName': 'WSCV1DED', 'ProfileType': 'Loc', 'FMLevel': 1, 'FMLevelName': 'Coverage', 'FieldName': 'CoverageDeductible'}, 'OCCSCHEME': {}, 'WSCV5LIMIT': {}, 'WSCV6DED': {}, 'WSCV4DED': {'PerilID': 1, 'DeductibleType': 'B', 'CoverageTypeID': 1, 'FMTermGroupID': 2, 'FMTermType': 'Deductible', 'ProfileElementName': 'WSCV4DED', 'ProfileType': 'Loc', 'FMLevel': 1, 'FMLevelName': 'Coverage', 'FieldName': 'CoverageDeductible'}, 'YEARBUILT': {}, 'WSCV2LIMIT': {}, 'WSCV10LMT': {}, 'WSCV4VAL': {'PerilID': 1, 'FMTermGroupID': 2, 'CoverageTypeID': 1, 'ProfileType': 'Loc', 'FMTermType': 'TIV', 'ProfileElementName': 'WSCV4VAL', 'FMLevel': 1, 'FMLevelName': 'Coverage', 'FieldName': 'TIV'}, 'STATECODE': {}, 'COUNTRY': {}, 'OCCTYPE': {}, 'WSCV6VAL': {}, 'WSCV10DED': {}, 'BLDGSCHEME': {}, 'WSCV8LIMIT': {}, 'NUMSTORIES': {}, 'COUNTRYGEOID': {}, 'WSSITEDED': {'DeductibleType': 'B', 'FMTermGroupID': 1, 'ProfileType': 'Loc', 'FMTermType': 'Deductible', 'ProfileElementName': 'WSSITEDED', 'FMLevel': 3, 'FMLevelName': 'Site', 'FieldName': 'SiteDeductible'}, 'WSCV10VAL': {}, 'WSCV7DED': {}, 'ACCNTNUM': {'FieldName': 'AccountNumber', 'ProfileType': 'Loc', 'ProfileElementName': 'ACCNTNUM'}, 'WSCV8VAL': {}, 'ROW_ID': {'FieldName': 'LocationID', 'ProfileType': 'Loc', 'ProfileElementName': 'ROW_ID'}, 'WSCOMBINEDLIM': {'FMTermGroupID': 1, 'ProfileType': 'Loc', 'FMTermType': 'Limit', 'ProfileElementName': 'WSCOMBINEDLIM', 'FMLevel': 2, 'FMLevelName': 'Combined', 'FieldName': 'CombinedLimit'}, 'COUNTY': {}, 'LONGITUDE': {}, 'CRESTA': {}}, 'source_exposures_validation_file_path': '/home/bloemkoli/OasisPiWind/flamingo/PiWind/Files/ValidationFiles/Generic_Windstorm_SourceLoc.xsd', 'oasis_files_path': '/tmp/analysis_test/tmp', 'lookup': <keys_server.PiWind.PiWindKeysLookup.PiWindKeysLookup object at 0x7f385d007be0>, 'source_exposures_file_path': '/home/bloemkoli/OasisPiWind/tests/data/SourceLocPiWind10K.csv', 'canonical_exposures_validation_file_path': '/home/bloemkoli/OasisPiWind/flamingo/PiWind/Files/ValidationFiles/Generic_Windstorm_CanLoc_B.xsd', 'canonical_exposures_profile_json_path': '/home/bloemkoli/OasisPiWind/oasislmf-piwind-canonical-loc-profile.json', 'source_to_canonical_exposures_transformation_file_path': '/home/bloemkoli/OasisPiWind/flamingo/PiWind/Files/TransformationFiles/MappingMapToGeneric_Windstorm_CanLoc_A.xslt', 'oasis_files_pipeline': <class 'oasislmf.exposures.pipeline.OasisFilesPipeline'>: {'_model_exposures_file_path': None, '_model_key': 'OasisLMF/PiWind/0.0.0.1', '_oasis_files': {'gulsummaryxref': None, 'coverages': None, 'items': None}, '_items_file_path': None, '_source_exposures_file_path': None, '_keys_error_file_path': None, '_gulsummaryxref_file_path': None, '_coverages_file_path': None, '_canonical_exposures_file_path': None, '_keys_file_path': None, '_file_paths': ('source_exposures_file_path', 'canonical_exposures_file_path', 'model_exposures_file_path', 'keys_file_path', 'keys_error_file_path', 'items_file_path', 'coverages_file_path', 'gulsummaryxref_file_path')}, 'canonical_to_model_exposures_transformation_file_path': '/home/bloemkoli/OasisPiWind/flamingo/PiWind/Files/TransformationFiles/MappingMapTopiwind_modelloc.xslt'}}: OasisLMF/PiWind/0.0.0.1
Setting up Oasis files directory for model OasisLMF/PiWind/0.0.0.1
Generating Oasis files for model
Checking output files directory exists for model
Checking for source exposures file
Copying source exposures file to input files directory
Generating canonical exposures file /tmp/analysis_test/tmp/canexp-20180620134838.csv
Generating model exposures file /tmp/analysis_test/tmp/modexp-20180620134838.csv
Generating keys file /tmp/analysis_test/tmp/oasiskeys-20180620134838.csv and keys error file /tmp/analysis_test/tmp/oasiskeys-errors-20180620134838.csv
keys_file_path=/tmp/analysis_test/tmp/oasiskeys-20180620134838.csv, keys_error_file_path=/tmp/analysis_test/tmp/oasiskeys-errors-20180620134838.csv
keys=<generator object OasisKeysLookupFactory.get_keys at 0x7f385cfaeeb8>
STARTED: keys_server.PiWind.PiWindKeysLookup.process_locations
COMPLETED: keys_server.PiWind.PiWindKeysLookup.process_locations in 0.0s
Generating Oasis files for model
Traceback (most recent call last):
  File "/home/bloemkoli/anaconda3/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/oasislmf/cmd/root.py", line 36, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/oasislmf/cmd/model.py", line 621, in action
    gen_oasis_files_cmd.action(args)
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/oasislmf/cmd/model.py", line 407, in action
    logger=self.logger,
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/oasislmf/exposures/manager.py", line 687, in start_files_pipeline
    return self.generate_oasis_files(oasis_model=oasis_model, **kwargs)
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/oasislmf/exposures/manager.py", line 594, in generate_oasis_files
    data_frame = self.load_master_data_frame(**kwargs)
  File "/home/bloemkoli/anaconda3/lib/python3.5/site-packages/oasislmf/exposures/manager.py", line 464, in load_master_data_frame
    [v for v in six.itervalues(canonical_exposures_profile) if v and v.get('FieldName').lower() == 'tiv']
TypeError: unorderable types: dict() < dict()
```

Sandeep Murthy from the oasislmf team indicated to me that:

> This appears to be an error caused by this line (#463 in oasislmf/exposures/manager.py)
> 
>     tiv_fields = tuple(sorted(
>         [v for v in six.itervalues(canonical_exposures_profile) if v and v.get('FieldName').lower() == 'tiv']
>       ))
> 
> So the sort operation is on a list of dicts and it appears as if dicts cannot be so ordered in Python 3,
> unlike Python 2 where this causes no problems.

**Comment by sr-murthy** [comment]
@martvdmarel This is a problem with the `oasislmf` package, not PiWind. Closing. I will be publishing a new release of `oasislmf` shortly with a fix for this problem. You should upgrade your installed version by using `pip install -U oasislmf`.
