### ISSUE TITLE
No `InuringPriority` column in the test RI info. file

### ISSUE THREAD

**Issue by sr-murthy** [OasisLMF/OasisPiWind#26]
@johcarter The test RI info. file that you added

https://github.com/OasisLMF/OasisPiWind/blob/master/tests/data/SourceReinsInfoOEDPiWind.csv

doesn't contain a column named `InuringPriority`, which is referenced in the RI module in the MDK

https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/exposures/reinsurance_layer.py#L44

This is causing the Oasis files generation command to fail, which means the model run command fails.

    ...
    Writing GUL files
   
    Writing FM files
    Generating reinsurance files
    Traceback (most recent call last):
    ...
      File "/Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/oasislmf-venv/src/oasislmf/oasislmf/cmd/model.py", line 641, in action
        oasis_fp
      File "/Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/oasislmf-venv/src/oasislmf/oasislmf/exposures/reinsurance_layer.py", line 109, in generate_files_for_reinsurance
        for inuring_priority in range(1, ri_info_df['InuringPriority'].max() + 1):
      File "/Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/oasislmf-venv/lib/python2.7/site-packages/pandas/core/frame.py", line 2139, in __getitem__
        return self._getitem_column(key)
      File "/Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/oasislmf-venv/lib/python2.7/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
        return self._get_item_cache(key)
      File "/Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/oasislmf-venv/lib/python2.7/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
        values = self._data.get(item)
      File "/Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/oasislmf-venv/lib/python2.7/site-packages/pandas/core/internals.py", line 3843, in get
        loc = self.items.get_loc(item)
      File "/Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/oasislmf-venv/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
        return self._engine.get_loc(self._maybe_cast_indexer(key))
      File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
      File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
      File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
      File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
    KeyError: 'InuringPriority'

These kinds of errors can be avoided by having robust code which uses metadata, rather than hardcoded column names, to process the RI source data. The RI backend code should really be using an RI profile, similar to the canonical profiles or aggregation profiles used in the exposure manager. But the RI implementation isn't mine, so I will leave it at that.

**Comment by johcarter** [comment]
done

**Comment by sr-murthy** [comment]
Thanks
